create table if not exists "TelegramGroups"
(
    telegram_id    bigint generated by default as identity not null,
    created_at     timestamp with time zone                null     default now(),
    wm             text                                    not null default 'Привет\!'::text,
    last_wm_id     bigint                                  not null default '-1'::bigint,
    bot_enabled    boolean                                 not null default true,
    title          character varying                       not null default ''::character varying,
    username       character varying                       null,
    type           character varying                       null,
    invite_link    character varying                       null,
    member_count   bigint                                  not null default '0'::bigint,
    administrators bigint[]                                null,
    constraint TelegramGroups_pkey primary key (telegram_id),
    constraint TelegramGroups_id_key unique (telegram_id)
) tablespace pg_default;