create table if not exists "TelegramUsers"
(
    telegram_id        bigint generated by default as identity not null,
    created_at         timestamp with time zone                null default now(),
    consists_of_groups bigint[]                                not null,
    username           character varying                       null,
    first_name         character varying                       null,
    last_name          character varying                       null,
    bio                text                                    null,
    is_bot             boolean                                 null,
    constraint TelegramUsers_pkey primary key (telegram_id)
) tablespace pg_default;